### ISSUE TITLE
Python error when in current release. 

### ISSUE THREAD

**Issue by DanGrandquist** [benedwards44/packagebuilder#1]
There was an error processing your request: Traceback (most recent call last): File "/app/buildpackage/tasks.py", line 100, in query_components_from_org for component in metadata_client.service.listMetadata(child_component_list,api_version): File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 542, in __call__ return client.invoke(args, kwargs) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 602, in invoke result = self.send(soapenv) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 649, in send result = self.failed(binding, e) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 702, in failed r, p = binding.get_fault(reply) File "/app/.heroku/python/lib/python2.7/site-packages/suds/bindings/binding.py", line 265, in get_fault raise WebFault(p, faultroot) WebFault: Server raised fault: 'UNKNOWN_EXCEPTION: invalid parameter value'

**Comment by benedwards44** [comment]
@DanGrandquist I wasn't able to replicate this error on my test Org. It could be something to the Org you are trying to run it against.

**Comment by kapuanil84** [comment]
here was an error processing your request: Traceback (most recent call last): File "/app/buildpackage/tasks.py", line 100, in query_components_from_org for component in metadata_client.service.listMetadata(child_component_list,api_version): File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 542, in __call__ return client.invoke(args, kwargs) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 602, in invoke result = self.send(soapenv) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 649, in send result = self.failed(binding, e) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 702, in failed r, p = binding.get_fault(reply) File "/app/.heroku/python/lib/python2.7/site-packages/suds/bindings/binding.py", line 265, in get_fault raise WebFault(p, faultroot) WebFault: Server raised fault: 'UNKNOWN_EXCEPTION: invalid parameter value'
