### ISSUE TITLE
Package Builder error related to missing version number

### ISSUE THREAD

**Issue by admillican08** [benedwards44/packagebuilder#17]
I tried using Package Builder in my Enterprise Production org, currently on the Spring '19 release, API version 45, and received this error:

There was an error processing your request: 

Traceback (most recent call last): File "/app/buildpackage/tasks.py", line 218, in query_components_from_org appendVersionNumForMissingFlows(package,metadata_client) File "/app/buildpackage/tasks.py", line 237, in appendVersionNumForMissingFlows flowAndVersionNumObj = getActiveVersionNumForFlows(metadata_client,flowNamesList) File "/app/buildpackage/tasks.py", line 257, in getActiveVersionNumForFlows flowAndVersionNumObj[resultObj.fullName] = resultObj.activeVersionNumber AttributeError: FlowDefinition instance has no attribute 'activeVersionNumber'

**Comment by sfdcale** [comment]
I know why this is happening. I will submit a PR tonight.

cc: @benedwards44

**Comment by sfdcale** [comment]
#18 will resolve this issue.

cc: @benedwards44

**Comment by sfdcale** [comment]
@admillican08 
I tested with my developer edition org and this error is gone now.

**Comment by admillican08** [comment]
@sfdcale : Yes, thank you, I was able to run this successfully in my production org this morning.
