### ISSUE TITLE
Package.xml Builder Error

### ISSUE THREAD

**Issue by harishmuppala** [benedwards44/packagebuilder#9]
I'm getting the below error when using package.xml Builder. **My org API version is 43.0**

There was an error processing your request: Traceback (most recent call last): File "/app/buildpackage/tasks.py", line 103, in query_components_from_org for component in metadata_client.service.listMetadata(child_component_list,api_version): File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 542, in __call__ return client.invoke(args, kwargs) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 602, in invoke result = self.send(soapenv) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 649, in send result = self.failed(binding, e) File "/app/.heroku/python/lib/python2.7/site-packages/suds/client.py", line 702, in failed r, p = binding.get_fault(reply) File "/app/.heroku/python/lib/python2.7/site-packages/suds/bindings/binding.py", line 265, in get_fault raise WebFault(p, faultroot) WebFault: Server raised fault: 'UNKNOWN_EXCEPTION: invalid parameter value'
Please return to the home page and try again. 

I have used this tool in other Sandboxes and it was working fine. Not sure what is different in the current Sandbox that the tool is not working. 
Thanks for your help!

**Comment by knightforce** [comment]
Same

**Comment by knightforce** [comment]
@benedwards44 - I know this isn't supported but any idea what is causing this error? The reason being I'm in the weeds of a project and could really use this! :)

**Comment by sfdcnoob** [comment]
@knightforce , Is it still happening with your org?
